services:
  mosquitto:
    image: eclipse-mosquitto:latest
    container_name: mosquitto
    restart: unless-stopped
    ports:
      - "1884:1883"
      # - "9001:9001"
    # volumes:
    #   - ./mosquitto:/etc/mosquitto
    #   - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf

